version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day-of-month: 1

    groups:
      typescript:
        patterns:
          - typescript
          - ts-node
          - tslib
          - '@types/*'

      other-deps:
        patterns:
          - '*'
        exclude-patterns:
          - typescript
          - ts-node
          - tslib
          - '@types/*'

    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-patch

    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
