template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "Features"
    labels:
      - "feature"
    commit-message:
      - "/^feat/i"
  - title: "Fixes"
    labels:
      - "bug"
    commit-message:
      - "/^fix/i"
  - title: "Maintenance"
    labels:
      - "chore"
    commit-message:
      - "/^chore/i"
change-template: "- $TITLE (#$NUMBER)"
no-changes-template: "- No changes"

autolabeler:
  - label: "feature"
    files:
      - "src/**"
  - label: "chore"
    files:
      - ".github/**"

exclude-labels:
  - "skip-changelog"
version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "fix"
  default: patch
