# [Dev Container Features](https://containers.dev/features)
# For format details, see https://containers.dev/implementors/json_reference/
# For config options, see the README at https://github.com/devcontainers/features

# This Dockerfile installs any additional OS packages, global tools, or other setup needed.
# The base image is set in devcontainer.json.

FROM mcr.microsoft.com/devcontainers/javascript-node:20

# Install any additional OS packages you need here
# RUN apt-get update && apt-get install -y <your-package-list>

# [Optional] Install additional global node packages
# RUN npm install -g <your-global-package>
